### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by CoolSpot** [nitrocode/CoinTaxes#3]
Sorting the buy and sell orders by time
Traceback (most recent call last):
  File "CoinTaxes.py", line 166, in <module>
    main()
  File "CoinTaxes.py", line 135, in main
    buys_sorted = sorted(buys, key=lambda buy_order: buy_order['order_time'])
  File "CoinTaxes.py", line 135, in <lambda>
    buys_sorted = sorted(buys, key=lambda buy_order: buy_order['order_time'])
TypeError: list indices must be integers, not str

I suspect it was caused by fix_orders() because it appends lists instead of objects into buys and sells lists.

**Comment by nitrocode** [comment]
Thanks for finding this! I'll have to step through when I have some more time. As always, PRs are accepted.

**Comment by robbpf** [comment]
Having similar issues with the latest commits available, any thoughts?

Normal Mode
Connected to GDAX.
Traceback (most recent call last):
  File "C:/Users/XXXX/PycharmProjects/CoinTaxes/CoinTaxes.py", line 160, in <module>
    main()
  File "C:/Users/XXXX/PycharmProjects/CoinTaxes/CoinTaxes.py", line 113, in main
    exchange_buys, exchange_sells = exchange.get_buys_sells()
  File "C:\Users\XXXX\PycharmProjects\CoinTaxes\exchanges\gdax_reader.py", line 140, in get_buys_sells
    if account['currency'] == 'USD':
TypeError: string indices must be integers

Debug Mode
C:\Users\XXXX\AppData\Local\Programs\Python\Python36-32\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 64403 --file C:/Users/XXXX/PycharmProjects/CoinTaxes/CoinTaxes.py
pydev debugger: process 437820 is connecting

Connected to pydev debugger (build 181.4668.75)
Connected to GDAX.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/XXXX/PycharmProjects/CoinTaxes/CoinTaxes.py", line 160, in <module>
    main()
  File "C:/Users/XXXX/PycharmProjects/CoinTaxes/CoinTaxes.py", line 113, in main
    exchange_buys, exchange_sells = exchange.get_buys_sells()
  File "C:\Users\XXXX\PycharmProjects\CoinTaxes\exchanges\gdax_reader.py", line 140, in get_buys_sells
    if account['currency'] == 'USD':
TypeError: string indices must be integers

Process finished with exit code 1

**Comment by nitrocode** [comment]
@CoolSpot @robbpf apologies. It's been a while since I've updated. Do you still notice this issue?

**Comment by CoolSpot** [comment]
Yes, it is still in latest master.
